In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 5.0035e+03,  4.5761e-41,  2.7208e-37],
        [ 0.0000e+00,  6.4653e+03,  4.5761e-41],
        [ 1.5302e-38,  0.0000e+00,  1.5301e-38],
        [ 0.0000e+00,  7.0743e+03,  4.5761e-41],
        [ 6.8872e+03,  4.5761e-41, -2.9469e+16]])


In [5]:
x = torch.tensor([5.5, 4])
print(x)

tensor([ 5.5000,  4.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.float64)
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float64)
print(x)

tensor([[ 2.0108, -0.1840,  1.0906],
        [-0.2107,  0.0924,  0.6469],
        [-0.7566, -0.6914,  0.9143],
        [ 0.0324, -0.0143,  0.8624],
        [ 1.3671, -0.2435,  0.0772]], dtype=torch.float64)


In [9]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3, dtype=torch.float64)
print(x + y)

tensor([[ 2.2578,  0.0986,  1.1847],
        [-0.0200,  0.3334,  0.8497],
        [-0.5126, -0.5443,  1.5734],
        [ 0.8593,  0.4501,  1.1288],
        [ 1.5746, -0.0761,  0.5072]], dtype=torch.float64)


In [13]:
print(torch.add(x, y))

tensor([[ 2.2578,  0.0986,  1.1847],
        [-0.0200,  0.3334,  0.8497],
        [-0.5126, -0.5443,  1.5734],
        [ 0.8593,  0.4501,  1.1288],
        [ 1.5746, -0.0761,  0.5072]], dtype=torch.float64)


In [15]:
result = torch.empty(5, 3, dtype=torch.float64)
torch.add(x, y, out = result)
print(result)

tensor([[ 2.2578,  0.0986,  1.1847],
        [-0.0200,  0.3334,  0.8497],
        [-0.5126, -0.5443,  1.5734],
        [ 0.8593,  0.4501,  1.1288],
        [ 1.5746, -0.0761,  0.5072]], dtype=torch.float64)


In [16]:
result = y.add_(x)
print(result)

tensor([[ 2.2578,  0.0986,  1.1847],
        [-0.0200,  0.3334,  0.8497],
        [-0.5126, -0.5443,  1.5734],
        [ 0.8593,  0.4501,  1.1288],
        [ 1.5746, -0.0761,  0.5072]], dtype=torch.float64)


In [17]:
print(result[:,1])

tensor([ 0.0986,  0.3334, -0.5443,  0.4501, -0.0761], dtype=torch.float64)


In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.5039])
-1.5038974285125732


In [20]:
a = torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[2. 2. 2. 2. 2.]


In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [25]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([-0.5039], device='cuda:0')
tensor([-0.5039], dtype=torch.float64)


### Adagrad
### Tensor and Gradients

In [27]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])


In [28]:
y = x + 2
print(y)

tensor([[ 3.,  3.],
        [ 3.,  3.]])


In [29]:
print(y.grad_fn)

In [30]:
z = y*y*3
out = z.mean()

print(z, out)

tensor([[ 27.,  27.],
        [ 27.,  27.]]) tensor(27.)


In [31]:
out.backward()

In [36]:
print("x is:{}\n\nx grad: {}".format(x, x.grad))

x is:tensor([[ 1.,  1.],
        [ 1.,  1.]])

x grad: tensor([[ 4.5000,  4.5000],
        [ 4.5000,  4.5000]])


In [37]:
x = torch.randn(3, requires_grad = True)

y = x*2
while y.data.norm() < 1000:
    y = y*2
    
print(y)

tensor([ 1103.1080,    47.1236,  1081.4652])


In [38]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(gradients)

print(x.grad)

tensor([  102.4000,  1024.0000,     0.1024])


In [40]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
